// ─── Component Catalog ────────────────────────────────────────────────────────
// Auto-generated by scripts/catalog.ts — DO NOT EDIT MANUALLY.
// This is the canonical source of truth for component classification.
// To add a component: place it in the correct tier folder, then run:
//   npx tsx scripts/catalog.ts
// Then add barrel exports to components/index.ts.

export const componentCatalog = {
  atoms:   [    'Avatar', 'Badge', 'BreadcrumbItem', 'Button', 'ChatBubble',
        'Checkbox', 'Chip', 'ColorSwatch', 'Divider', 'EmptyState',
        'FileInput', 'Heading', 'Image', 'Input', 'Item',
        'Label', 'Link', 'List', 'NavItem', 'ProgressBar',
        'ProgressIndicator', 'Quote', 'Radio', 'Rating', 'SegmentedControl',
        'Select', 'Skeleton', 'Slider', 'Spinner',
        'Stack', 'Switch', 'Tag', 'Textarea', 'ThemeSwitcher',
        'Toggle', 'TreeItem', 'TypingIndicator', 'Video'],
  molecules:   [    'AlertBanner', 'Breadcrumb', 'ButtonGroup', 'Calendar', 'Card',
        'ChatHeader', 'ChatInputBar', 'ChatMessage', 'Combobox', 'DateInput',
        'DropdownMenu', 'Fieldset', 'FileUpload', 'FormField', 'InputGroup',
        'Navbar', 'NumberInput', 'Pagination', 'Popover', 'ProductCard',
        'RadioGroup', 'SearchBar', 'StatCard', 'Stepper', 'Toast',
        'Tooltip', 'TreeView'],
  organisms:   [    'Accordion', 'AreaChart', 'BarChart', 'Carousel', 'Chat',
        'ColorPicker', 'DataTable', 'Datepicker', 'Drawer', 'Footer',
        'Form', 'Header', 'Modal', 'PieChart', 'Sidebar',
        'Tabs'],
} as const

// ─── Typed helpers ──────────────────────────────────────────────────────────────

export type ComponentName =
  | (typeof componentCatalog.atoms)[number]
  | (typeof componentCatalog.molecules)[number]
  | (typeof componentCatalog.organisms)[number]

export type ComponentLevel = 'atom' | 'molecule' | 'organism'

export function getComponentLevel(name: string): ComponentLevel | undefined {
  if (componentCatalog.atoms.includes(name as any)) return 'atom'
  if (componentCatalog.molecules.includes(name as any)) return 'molecule'
  if (componentCatalog.organisms.includes(name as any)) return 'organism'
  return undefined
}
