#!/usr/bin/env node
/**
 * Catalog Script — auto-discovers components and regenerates components/catalog.ts
 *
 * Scans components/atoms/, molecules/, organisms/ for existing component folders
 * and writes the canonical catalog. The Token Editor and Docs Site derive their
 * component lists from catalog.ts at import time, so no other files need updating.
 *
 * After running this script, manually add barrel exports to components/index.ts
 * for any newly discovered components.
 *
 * Usage:
 *   npx tsx scripts/catalog.ts
 *
 * Safety: reads before writing, shows diff summary, never deletes entries.
 */

import fs from 'fs/promises'
import path from 'path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT = path.resolve(__dirname, '..')
const COMPONENTS_DIR = path.join(ROOT, 'components')
const CATALOG_FILE = path.join(ROOT, 'components/catalog.ts')

const TIERS = [
  { name: 'atoms', level: 'atom' },
  { name: 'molecules', level: 'molecule' },
  { name: 'organisms', level: 'organism' },
]

interface ComponentInfo {
  name: string
  level: string
}

async function scanComponents(): Promise<ComponentInfo[]> {
  const result: ComponentInfo[] = []

  for (const { name, level } of TIERS) {
    const tierDir = path.join(COMPONENTS_DIR, name)
    try {
      const entries = await fs.readdir(tierDir, { withFileTypes: true })
      for (const entry of entries) {
        if (entry.isDirectory()) {
          const tsxPath = path.join(tierDir, entry.name, `${entry.name}.tsx`)
          try {
            await fs.access(tsxPath)
            result.push({ name: entry.name, level })
          } catch {
            // No TSX file — skip
          }
        }
      }
    } catch {
      // Tier folder doesn't exist
    }
  }

  return result.sort((a, b) => a.name.localeCompare(b.name))
}

function generateCatalog(components: ComponentInfo[]): string {
  const atoms = components.filter(c => c.level === 'atom').map(c => c.name).sort()
  const molecules = components.filter(c => c.level === 'molecule').map(c => c.name).sort()
  const organisms = components.filter(c => c.level === 'organism').map(c => c.name).sort()

  const formatSection = (items: string[]): string => {
    if (items.length === 0) return '  []'
    const chunked: string[] = []
    for (let i = 0; i < items.length; i += 5) {
      chunked.push(`    '${items.slice(i, i + 5).join("', '")}'`)
    }
    return `  [${chunked.join(',\n    ')}]`
  }

  const allAtoms = atoms.map(n => `  ${n}: 'atom'`)
  const allMolecules = molecules.map(n => `  ${n}: 'molecule'`)
  const allOrganisms = organisms.map(n => `  ${n}: 'organism'`)

  return `// ─── Component Catalog ────────────────────────────────────────────────────────
// Auto-generated by scripts/catalog.ts — DO NOT EDIT MANUALLY.
// This is the canonical source of truth for component classification.
// To add a component: place it in the correct tier folder, then run:
//   npx tsx scripts/catalog.ts
// Then add barrel exports to components/index.ts.

export const componentCatalog = {
  atoms: ${formatSection(atoms)},
  molecules: ${formatSection(molecules)},
  organisms: ${formatSection(organisms)},
} as const

// ─── Typed helpers ──────────────────────────────────────────────────────────────

export type ComponentName =
  | (typeof componentCatalog.atoms)[number]
  | (typeof componentCatalog.molecules)[number]
  | (typeof componentCatalog.organisms)[number]

export type ComponentLevel = 'atom' | 'molecule' | 'organism'

export function getComponentLevel(name: string): ComponentLevel | undefined {
  if (componentCatalog.atoms.includes(name as any)) return 'atom'
  if (componentCatalog.molecules.includes(name as any)) return 'molecule'
  if (componentCatalog.organisms.includes(name as any)) return 'organism'
  return undefined
}
`
}

async function main() {
  console.log('📦 Scanning components directory...\n')

  const components = await scanComponents()

  console.log(`Found ${components.length} components:`)
  console.log(`  Atoms:     ${components.filter(c => c.level === 'atom').length}`)
  console.log(`  Molecules: ${components.filter(c => c.level === 'molecule').length}`)
  console.log(`  Organisms: ${components.filter(c => c.level === 'organism').length}\n`)

  const newCatalog = generateCatalog(components)

  // Show what needs attention
  console.log('📝 Summary:\n')
  console.log(`  ✓ Catalog will be updated with ${components.length} entries\n`)

  // Read existing catalog for comparison
  let existingCatalog = ''
  try {
    existingCatalog = await fs.readFile(CATALOG_FILE, 'utf-8')
  } catch {
    // File doesn't exist yet
  }

  // Update catalog file
  await fs.writeFile(CATALOG_FILE, newCatalog, 'utf-8')
  console.log(`  ✓ Updated: ${path.relative(ROOT, CATALOG_FILE)}\n`)

  // Check index.ts for missing barrel exports
  const INDEX_FILE = path.join(ROOT, 'components/index.ts')
  try {
    const indexContent = await fs.readFile(INDEX_FILE, 'utf-8')
    const missing: string[] = []
    for (const c of components) {
      const exportLine = `export * from './${c.level === 'atom' ? 'atoms' : c.level === 'molecule' ? 'molecules' : 'organisms'}/${c.name}/${c.name}'`
      if (!indexContent.includes(exportLine)) {
        missing.push(c.name)
      }
    }
    if (missing.length > 0) {
      console.log(`  ⚠  Missing barrel exports in components/index.ts for:`)
      for (const name of missing) {
        const tier = components.find(c => c.name === name)!.level
        const folder = tier === 'atom' ? 'atoms' : tier === 'molecule' ? 'molecules' : 'organisms'
        console.log(`       export * from './${folder}/${name}/${name}'`)
        console.log(`       export type * from './${folder}/${name}/${name}.types'`)
      }
      console.log()
    } else {
      console.log('  ✓ All barrel exports present in components/index.ts\n')
    }
  } catch {
    console.log('  ⚠  Could not read components/index.ts — check barrel exports manually\n')
  }

  console.log('✅ Catalog synced successfully!')
}

main().catch((err) => {
  console.error('❌ Catalog failed:', err.message)
  process.exitCode = 1
})
